# Generated by Django 2.2.7 on 2019-11-24 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Flor',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('descripcion', models.IntegerField()),
                ('fotografia', models.ImageField(null=True, upload_to='florcitas')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flor.Estado')),
            ],
        ),
    ]
